# Generated by Django 3.1 on 2020-08-12 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='home',
            new_name='contactForm',
        ),
    ]
