# Generated by Django 3.1 on 2020-08-12 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200812_1147'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contactForm',
            new_name='contact',
        ),
    ]
