# Generated by Django 3.1 on 2020-08-12 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200812_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='username',
        ),
    ]
