# Generated by Django 3.1 on 2020-08-12 08:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200812_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
