# Generated by Django 3.1 on 2020-08-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='cv',
            field=models.CharField(default='null', max_length=1000),
            preserve_default=False,
        ),
    ]
